import { ThemeDefinition } from '@/types/theme';

export const PRESET_THEMES: ThemeDefinition[] = [
  {
    id: 'synapse-obsidian',
    name: 'Synapse Obsidian',
    description: 'Deep obsidian workspace with sleek indigo-violet accents and clean contrast.',
    type: 'dark',
    tags: ['Default', 'Modern', 'Minimal'],
    previewColors: {
      bg: '#13141a',
      card: '#191a22',
      primary: '#7b81dc',
      accent: '#262834',
      text: '#e1e3ec',
    },
    colors: {
      background: '#13141a',
      foreground: '#e1e3ec',
      card: '#191a22',
      cardForeground: '#e1e3ec',
      popover: '#1d1e27',
      popoverForeground: '#e1e3ec',
      primary: '#7b81dc',
      primaryForeground: '#ffffff',
      secondary: '#21232d',
      secondaryForeground: '#b3b7c8',
      muted: '#1c1d26',
      mutedForeground: '#84899c',
      accent: '#262834',
      accentForeground: '#eef0f8',
      destructive: '#db5555',
      destructiveForeground: '#ffffff',
      border: '#262836',
      input: '#1f212b',
      ring: '#7b81dc',
      sidebar: '#15161c',
      sidebarBorder: '#262836',
      heading: '#f0f2fa',
      heading1: '#ffffff',
      heading2: '#c5c9ed',
      heading3: '#9ea5d6',
    },
  },
  {
    id: 'midnight-cyber',
    name: 'Midnight Cyber',
    description: 'Ultra-deep space navy paired with radiant electric cyan and neon teal glows.',
    type: 'dark',
    tags: ['Cyber', 'Tech', 'High-Contrast'],
    previewColors: {
      bg: '#0a0e17',
      card: '#111827',
      primary: '#06b6d4',
      accent: '#1e293b',
      text: '#f1f5f9',
    },
    colors: {
      background: '#0a0e17',
      foreground: '#f1f5f9',
      card: '#111827',
      cardForeground: '#f1f5f9',
      popover: '#162032',
      popoverForeground: '#f1f5f9',
      primary: '#06b6d4',
      primaryForeground: '#021019',
      secondary: '#1f293d',
      secondaryForeground: '#94a3b8',
      muted: '#131c2e',
      mutedForeground: '#64748b',
      accent: '#1e293b',
      accentForeground: '#e2e8f0',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      border: '#1e293b',
      input: '#172236',
      ring: '#06b6d4',
      sidebar: '#0c121e',
      sidebarBorder: '#1e293b',
      heading: '#38bdf8',
      heading1: '#38bdf8',
      heading2: '#22d3ee',
      heading3: '#67e8f9',
    },
  },
  {
    id: 'tokyo-dusk',
    name: 'Tokyo Dusk',
    description: 'Atmospheric Japanese cyberpunk dusk with moody violet-black and vivid neon lavender.',
    type: 'dark',
    tags: ['Synthwave', 'Vibrant', 'Popular'],
    previewColors: {
      bg: '#12121e',
      card: '#1a1a2b',
      primary: '#a855f7',
      accent: '#26243d',
      text: '#e0def4',
    },
    colors: {
      background: '#12121e',
      foreground: '#e0def4',
      card: '#1a1a2b',
      cardForeground: '#e0def4',
      popover: '#201f34',
      popoverForeground: '#e0def4',
      primary: '#a855f7',
      primaryForeground: '#ffffff',
      secondary: '#242338',
      secondaryForeground: '#908caa',
      muted: '#1b1a2c',
      mutedForeground: '#6e6a86',
      accent: '#2b2844',
      accentForeground: '#f2e9e1',
      destructive: '#eb6f92',
      destructiveForeground: '#ffffff',
      border: '#2a2842',
      input: '#201f35',
      ring: '#a855f7',
      sidebar: '#141422',
      sidebarBorder: '#2a2842',
      heading: '#f3e8ff',
      heading1: '#f3e8ff',
      heading2: '#c084fc',
      heading3: '#a855f7',
    },
  },
  {
    id: 'nord-arctic',
    name: 'Nord Arctic',
    description: 'Serene Nordic polar night palette featuring arctic frost grays and glacier ice blues.',
    type: 'dark',
    tags: ['Nordic', 'Clean', 'Muted'],
    previewColors: {
      bg: '#1e222a',
      card: '#242933',
      primary: '#88c0d0',
      accent: '#2e3440',
      text: '#eceff4',
    },
    colors: {
      background: '#1e222a',
      foreground: '#eceff4',
      card: '#242933',
      cardForeground: '#eceff4',
      popover: '#2b313d',
      popoverForeground: '#eceff4',
      primary: '#88c0d0',
      primaryForeground: '#1e222a',
      secondary: '#2e3440',
      secondaryForeground: '#d8dee9',
      muted: '#252a35',
      mutedForeground: '#7b8394',
      accent: '#353c4a',
      accentForeground: '#eceff4',
      destructive: '#bf616a',
      destructiveForeground: '#ffffff',
      border: '#333a47',
      input: '#2b313d',
      ring: '#88c0d0',
      sidebar: '#20242d',
      sidebarBorder: '#333a47',
      heading: '#eceff4',
      heading1: '#eceff4',
      heading2: '#88c0d0',
      heading3: '#81a1c1',
    },
  },
  {
    id: 'emerald-matrix',
    name: 'Emerald Matrix',
    description: 'Deep midnight evergreen forest with electric matrix mint and glowing emerald badges.',
    type: 'dark',
    tags: ['Nature', 'Focus', 'Coding'],
    previewColors: {
      bg: '#0c1512',
      card: '#12201b',
      primary: '#10b981',
      accent: '#183027',
      text: '#ecfdf5',
    },
    colors: {
      background: '#0c1512',
      foreground: '#ecfdf5',
      card: '#12201b',
      cardForeground: '#ecfdf5',
      popover: '#162923',
      popoverForeground: '#ecfdf5',
      primary: '#10b981',
      primaryForeground: '#042f20',
      secondary: '#1b322a',
      secondaryForeground: '#a7f3d0',
      muted: '#13241e',
      mutedForeground: '#6ee7b7',
      accent: '#224036',
      accentForeground: '#f0fdf4',
      destructive: '#f87171',
      destructiveForeground: '#ffffff',
      border: '#1f3b31',
      input: '#152922',
      ring: '#10b981',
      sidebar: '#0e1815',
      sidebarBorder: '#1f3b31',
      heading: '#34d399',
      heading1: '#34d399',
      heading2: '#6ee7b7',
      heading3: '#a7f3d0',
    },
  },
  {
    id: 'dracula-gothic',
    name: 'Dracula Gothic',
    description: 'Legendary developer palette with deep gothic violet-slate, vivid magenta, and neon orchid.',
    type: 'dark',
    tags: ['Developer', 'Iconic', 'Dark'],
    previewColors: {
      bg: '#181726',
      card: '#212035',
      primary: '#bd93f9',
      accent: '#2d2b49',
      text: '#f8f8f2',
    },
    colors: {
      background: '#181726',
      foreground: '#f8f8f2',
      card: '#212035',
      cardForeground: '#f8f8f2',
      popover: '#27253f',
      popoverForeground: '#f8f8f2',
      primary: '#bd93f9',
      primaryForeground: '#1e1d2f',
      secondary: '#2d2b4a',
      secondaryForeground: '#e2e0f9',
      muted: '#1e1d30',
      mutedForeground: '#8985a8',
      accent: '#353357',
      accentForeground: '#ffffff',
      destructive: '#ff5555',
      destructiveForeground: '#ffffff',
      border: '#353356',
      input: '#26243e',
      ring: '#bd93f9',
      sidebar: '#1a192b',
      sidebarBorder: '#353356',
      heading: '#f8f8f2',
      heading1: '#f8f8f2',
      heading2: '#ff79c6',
      heading3: '#bd93f9',
    },
  },
  {
    id: 'sunset-amber',
    name: 'Sunset Amber',
    description: 'Warm obsidian basalt bathed in radiant sunset glow, golden amber and warm terracotta.',
    type: 'dark',
    tags: ['Warm', 'Cozy', 'Creative'],
    previewColors: {
      bg: '#171412',
      card: '#211d1a',
      primary: '#f59e0b',
      accent: '#332b24',
      text: '#fef3c7',
    },
    colors: {
      background: '#171412',
      foreground: '#fef3c7',
      card: '#211d1a',
      cardForeground: '#fef3c7',
      popover: '#28231f',
      popoverForeground: '#fef3c7',
      primary: '#f59e0b',
      primaryForeground: '#1a1003',
      secondary: '#2e2620',
      secondaryForeground: '#fde68a',
      muted: '#1f1a16',
      mutedForeground: '#a39281',
      accent: '#382e25',
      accentForeground: '#fffbeb',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#3b322a',
      input: '#27211c',
      ring: '#f59e0b',
      sidebar: '#191513',
      sidebarBorder: '#3b322a',
      heading: '#fbbf24',
      heading1: '#fbbf24',
      heading2: '#f59e0b',
      heading3: '#fcd34d',
    },
  },
  {
    id: 'rose-twilight',
    name: 'Rose Twilight',
    description: 'Velvety dusky plum, gentle rose-gold accents, and delicate mauve surface tones.',
    type: 'dark',
    tags: ['Elegant', 'Pastel', 'Soft'],
    previewColors: {
      bg: '#181216',
      card: '#221920',
      primary: '#f472b6',
      accent: '#33232f',
      text: '#fdf2f8',
    },
    colors: {
      background: '#181216',
      foreground: '#fdf2f8',
      card: '#221920',
      cardForeground: '#fdf2f8',
      popover: '#291e27',
      popoverForeground: '#fdf2f8',
      primary: '#f472b6',
      primaryForeground: '#26061a',
      secondary: '#31232e',
      secondaryForeground: '#fbcfe8',
      muted: '#20161e',
      mutedForeground: '#9d8494',
      accent: '#3b2938',
      accentForeground: '#fff',
      destructive: '#fb7185',
      destructiveForeground: '#ffffff',
      border: '#3b2837',
      input: '#281d26',
      ring: '#f472b6',
      sidebar: '#1b1318',
      sidebarBorder: '#3b2837',
      heading: '#fdf2f8',
      heading1: '#fdf2f8',
      heading2: '#f472b6',
      heading3: '#f9a8d4',
    },
  },
  {
    id: 'clean-studio-light',
    name: 'Clean Studio (Light)',
    description: 'Ultra-crisp modern architectural daylight canvas with sharp contrast and indigo accents.',
    type: 'light',
    tags: ['Light', 'Modern', 'High-Contrast'],
    previewColors: {
      bg: '#f8fafc',
      card: '#ffffff',
      primary: '#4f46e5',
      accent: '#e2e8f0',
      text: '#0f172a',
    },
    colors: {
      background: '#f8fafc',
      foreground: '#0f172a',
      card: '#ffffff',
      cardForeground: '#0f172a',
      popover: '#ffffff',
      popoverForeground: '#0f172a',
      primary: '#4f46e5',
      primaryForeground: '#ffffff',
      secondary: '#f1f5f9',
      secondaryForeground: '#334155',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      accent: '#e2e8f0',
      accentForeground: '#0f172a',
      destructive: '#e11d48',
      destructiveForeground: '#ffffff',
      border: '#e2e8f0',
      input: '#edf2f7',
      ring: '#4f46e5',
      sidebar: '#f1f5f9',
      sidebarBorder: '#e2e8f0',
      heading: '#0f172a',
      heading1: '#0f172a',
      heading2: '#312e81',
      heading3: '#4338ca',
    },
  },
  {
    id: 'warm-parchment-light',
    name: 'Warm Parchment (Light)',
    description: 'Gentle academic book paper, deep espresso typography, and warm terracotta ochre accents.',
    type: 'light',
    tags: ['Light', 'Reading', 'Sepia'],
    previewColors: {
      bg: '#f7f4ed',
      card: '#ffffff',
      primary: '#d97706',
      accent: '#ebe4d5',
      text: '#292524',
    },
    colors: {
      background: '#f7f4ed',
      foreground: '#292524',
      card: '#ffffff',
      cardForeground: '#292524',
      popover: '#ffffff',
      popoverForeground: '#292524',
      primary: '#d97706',
      primaryForeground: '#ffffff',
      secondary: '#ece5d8',
      secondaryForeground: '#44403c',
      muted: '#f0ebdF',
      mutedForeground: '#78716c',
      accent: '#e5dcce',
      accentForeground: '#1c1917',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#e2d8c7',
      input: '#eee7da',
      ring: '#d97706',
      sidebar: '#efe9dc',
      sidebarBorder: '#e2d8c7',
      heading: '#1c1917',
      heading1: '#1c1917',
      heading2: '#92400e',
      heading3: '#b45309',
    },
  },
];

export const DEFAULT_THEME_ID = 'synapse-obsidian';
