import { Template } from '@/types/domain';

export const BUILTIN_TEMPLATES: Array<Omit<Template, 'workspace_id'>> = [
  {
    id: 'tmpl-meeting',
    title: 'Meeting Notes & Action Items',
    description: 'Structured sync with agenda, attendees, discussion notes, and actionable next steps.',
    icon: '📅',
    content: {
      title: 'Meeting: {{title}} ({{date}})',
      blocks: [
        { type: 'heading_1', content: { text: 'Meeting Overview — {{date}}' } },
        { type: 'callout', content: { text: 'Organizer: {{user}} | Workspace: {{workspace}} | Date: {{date}} {{time}}' } },
        { type: 'heading_2', content: { text: 'Attendees' } },
        { type: 'bullet_list', content: { text: '{{user}} (Lead)' } },
        { type: 'bullet_list', content: { text: 'Key Collaborators' } },
        { type: 'heading_2', content: { text: 'Agenda & Key Discussion Points' } },
        { type: 'bullet_list', content: { text: 'Review roadmap milestones and active blockers' } },
        { type: 'bullet_list', content: { text: 'Architecture decisions & open questions' } },
        { type: 'bullet_list', content: { text: 'Next sprint deliverables alignment' } },
        { type: 'heading_2', content: { text: 'Action Items' } },
        { type: 'todo_list', content: { text: 'Follow up on API design and data contracts' } },
        { type: 'todo_list', content: { text: 'Update project timeline and documentation' } },
        { type: 'todo_list', content: { text: 'Schedule team follow-up sync' } },
      ],
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-rfc',
    title: 'Engineering RFC / Architecture Spec',
    description: 'Technical architecture document for proposing new systems, APIs, or architectural changes.',
    icon: '🛠️',
    content: {
      title: 'RFC: {{title}}',
      blocks: [
        { type: 'heading_1', content: { text: 'RFC: {{title}}' } },
        { type: 'callout', content: { text: 'Status: Draft | Author: {{user}} | Workspace: {{workspace}} | Date: {{date}}' } },
        { type: 'heading_2', content: { text: '1. Problem Statement & Motivation' } },
        { type: 'paragraph', content: { text: 'What problem are we solving, why is this important now, and what are the expected outcomes?' } },
        { type: 'heading_2', content: { text: '2. Proposed Architecture & Design' } },
        { type: 'paragraph', content: { text: 'Detailed architectural overview, component relationships, data flow, and error handling.' } },
        {
          type: 'code',
          content: { text: '// Architecture interface contract\ninterface ServiceResponse<T> {\n  data: T;\n  status: number;\n  timestamp: string;\n}' },
          properties: { language: 'typescript' },
        },
        { type: 'heading_2', content: { text: '3. Key Considerations & Trade-offs' } },
        { type: 'bullet_list', content: { text: 'Performance & latency guarantees' } },
        { type: 'bullet_list', content: { text: 'Fault tolerance & offline resilience' } },
        { type: 'bullet_list', content: { text: 'Data migration and backward compatibility' } },
        { type: 'heading_2', content: { text: '4. Alternatives Considered' } },
        { type: 'paragraph', content: { text: 'Options evaluated and rationale for choosing this approach.' } },
      ],
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-prd',
    title: 'Product Requirements Document (PRD)',
    description: 'Comprehensive product spec outlining user problems, user stories, success metrics, and MVP scope.',
    icon: '🚀',
    content: {
      title: 'PRD: {{title}}',
      blocks: [
        { type: 'heading_1', content: { text: 'PRD: {{title}}' } },
        { type: 'callout', content: { text: 'Product Lead: {{user}} | Status: In Review | Target Release: Upcoming' } },
        { type: 'heading_2', content: { text: 'Problem Statement' } },
        { type: 'paragraph', content: { text: 'What user problem are we solving? Back this up with qualitative user feedback or quantitative metrics.' } },
        { type: 'heading_2', content: { text: 'User Personas & Stories' } },
        { type: 'bullet_list', content: { text: 'As a collaborator, I want instant shared updates so that everyone stays in sync.' } },
        { type: 'bullet_list', content: { text: 'As a team lead, I want standardized templates to ensure documentation quality.' } },
        { type: 'heading_2', content: { text: 'MVP Scope & Key Deliverables' } },
        { type: 'todo_list', content: { text: 'P0: Core real-time editing & local-first persistence' } },
        { type: 'todo_list', content: { text: 'P0: Workspace invite and member permission controls' } },
        { type: 'todo_list', content: { text: 'P1: Interactive template gallery and blueprints' } },
        { type: 'heading_2', content: { text: 'Success Metrics (KPIs)' } },
        { type: 'bullet_list', content: { text: 'Daily active collaboration rate > 80%' } },
        { type: 'bullet_list', content: { text: 'Zero data loss rate across browser and network reconnects' } },
      ],
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-sprint',
    title: 'Sprint Planning & Retrospective',
    description: 'Sprint cycle tracker covering goals, backlog commitments, what went well, and action items.',
    icon: '📋',
    content: {
      title: 'Sprint Cycle: {{title}}',
      blocks: [
        { type: 'heading_1', content: { text: 'Sprint Planning & Review — {{date}}' } },
        { type: 'callout', content: { text: 'Facilitator: {{user}} | Workspace: {{workspace}} | Cycle: Active Sprint' } },
        { type: 'heading_2', content: { text: 'Sprint Goals' } },
        { type: 'bullet_list', content: { text: 'Deliver core feature milestone ahead of schedule' } },
        { type: 'bullet_list', content: { text: 'Ensure 0 regression defects on collaborative sync' } },
        { type: 'heading_2', content: { text: 'Committed Backlog' } },
        { type: 'todo_list', content: { text: 'Ship template system improvements' } },
        { type: 'todo_list', content: { text: 'Verify cross-client synchronization under latency' } },
        { type: 'todo_list', content: { text: 'Perform security & error state audit' } },
        { type: 'heading_2', content: { text: 'Retrospective: What Went Well 🎉' } },
        { type: 'bullet_list', content: { text: 'Rapid turnaround on member avatar sync and workspace badges' } },
        { type: 'heading_2', content: { text: 'Retrospective: Action Items 🔧' } },
        { type: 'todo_list', content: { text: 'Expand end-to-end integration test coverage' } },
      ],
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-standup',
    title: 'Daily Standup & Focus Journal',
    description: "Quick personal or team daily log: yesterday's wins, today's top priorities, and current blockers.",
    icon: '🧠',
    content: {
      title: 'Daily Standup — {{date}}',
      blocks: [
        { type: 'heading_1', content: { text: 'Standup: {{date}}' } },
        { type: 'callout', content: { text: 'Engineer: {{user}} | Date: {{date}}' } },
        { type: 'heading_2', content: { text: "Yesterday's Achievements" } },
        { type: 'bullet_list', content: { text: 'Closed assigned tickets and pushed verified commits' } },
        { type: 'heading_2', content: { text: "Today's Top 3 Priorities" } },
        { type: 'todo_list', content: { text: 'Priority 1: Implement template modal and engine fixes' } },
        { type: 'todo_list', content: { text: 'Priority 2: Code review open pull requests' } },
        { type: 'todo_list', content: { text: 'Priority 3: Update documentation and team sync' } },
        { type: 'heading_2', content: { text: 'Blockers & Dependencies' } },
        { type: 'paragraph', content: { text: 'No current blockers.' } },
      ],
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-wiki',
    title: 'Team Knowledge Base & Guide',
    description: 'Living team guide with onboarding instructions, architecture overviews, and FAQs.',
    icon: '📚',
    content: {
      title: 'Team Guide: {{title}}',
      blocks: [
        { type: 'heading_1', content: { text: 'Team Guide: {{title}}' } },
        { type: 'callout', content: { text: 'Curated by: {{user}} | Workspace: {{workspace}} | Updated: {{date}}' } },
        { type: 'heading_2', content: { text: '1. Overview & Purpose' } },
        { type: 'paragraph', content: { text: 'Welcome to this team guide. Use this document as the single source of truth for procedures, conventions, and resources.' } },
        { type: 'heading_2', content: { text: '2. Getting Started' } },
        { type: 'bullet_list', content: { text: 'Review team conventions and workspace structure' } },
        { type: 'bullet_list', content: { text: 'Request necessary access credentials and environment setups' } },
        { type: 'heading_2', content: { text: '3. Core Conventions & Guidelines' } },
        { type: 'paragraph', content: { text: 'All state transitions must adhere to local-first standards before server dispatch.' } },
        { type: 'heading_2', content: { text: '4. Frequently Asked Questions' } },
        { type: 'paragraph', content: { text: 'Q: How do templates work?\nA: Templates instantiate structured blocks with dynamic variable replacements into new notes.' } },
      ],
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tmpl-postmortem',
    title: 'Incident Postmortem & RCA',
    description: 'Blameless incident retrospective analyzing timeline, root cause, impact, and preventative action items.',
    icon: '🚨',
    content: {
      title: 'Incident Postmortem: {{title}}',
      blocks: [
        { type: 'heading_1', content: { text: 'Incident Postmortem: {{title}}' } },
        { type: 'callout', content: { text: 'Incident Lead: {{user}} | Workspace: {{workspace}} | Date: {{date}} | Severity: SEV-1' } },
        { type: 'heading_2', content: { text: 'Executive Summary' } },
        { type: 'paragraph', content: { text: 'Provide a concise overview of the event, system impact, duration, and final resolution.' } },
        { type: 'heading_2', content: { text: 'Timeline of Events' } },
        { type: 'bullet_list', content: { text: '{{time}} — Automated monitoring alert triggered' } },
        { type: 'bullet_list', content: { text: '{{time}} — Incident commander mobilized response team' } },
        { type: 'bullet_list', content: { text: '{{time}} — Root cause identified and mitigation patch applied' } },
        { type: 'bullet_list', content: { text: '{{time}} — Full system recovery verified' } },
        { type: 'heading_2', content: { text: 'Root Cause Analysis (5 Whys)' } },
        { type: 'paragraph', content: { text: 'Drill down through the 5 Whys to determine the systemic root cause.' } },
        { type: 'heading_2', content: { text: 'Preventative Action Items' } },
        { type: 'todo_list', content: { text: 'Add automated regression tests covering failure mode' } },
        { type: 'todo_list', content: { text: 'Enhance alert threshold and telemetry dashboard' } },
      ],
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
];

export function getBuiltinTemplates(workspaceId: string): Template[] {
  return BUILTIN_TEMPLATES.map((tmpl) => ({
    ...tmpl,
    id: `${tmpl.id}-${workspaceId}`,
    workspace_id: workspaceId,
  }));
}
